# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cucumber-farmer}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Scilipoti"]
  s.date = %q{2010-08-26}
  s.description = %q{A library of cucumber step definitions, which allow you to use a human to assert conditions during acceptance tests.
    For instance... we needed to verify that certain portions of an image were 'blacked out'.
    This is very difficult to assert using automation.  However, it is easy for a human.
    Farmer allows us to include human confirmation into our normal testing flow.
    }
  s.email = %q{matt@scilipoti.name}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "cucumber-farmer.gemspec",
     "lib/farmer.rb",
     "lib/farmer/step_definitions.rb",
     "test/helper.rb",
     "test_app/features/home_page.feature",
     "test_app/features/human_confirmation.feature",
     "test_app/features/step_definitions/web_steps.rb",
     "test_app/features/support/env.rb",
     "test_app/test_app.rb"
  ]
  s.homepage = %q{http://github.com/mattscilipoti/farmer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A library of cucumber step definitions, which allow you to use a human to assert conditions during acceptance tests.}
  s.test_files = [
    "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mattscilipoti-rdialog>, ["= 0.6.1"])
      s.add_development_dependency(%q<cucumber>, [">= 0.6"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10"])
    else
      s.add_dependency(%q<mattscilipoti-rdialog>, ["= 0.6.1"])
      s.add_dependency(%q<cucumber>, [">= 0.6"])
      s.add_dependency(%q<shoulda>, [">= 2.10"])
    end
  else
    s.add_dependency(%q<mattscilipoti-rdialog>, ["= 0.6.1"])
    s.add_dependency(%q<cucumber>, [">= 0.6"])
    s.add_dependency(%q<shoulda>, [">= 2.10"])
  end
end

